# Generated by Django 4.2.11 on 2025-06-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminprofile_profile_picture_department_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
