# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_achievement_activity_announcement_book_borrowedbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('normal', 'Normal User'), ('student', 'Student'), ('teacher', 'Teacher'), ('headmaster', 'Head of School'), ('admin', 'School Admin')],
                default='normal',
                max_length=20,
                verbose_name='Role'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='is_headmaster',
            field=models.BooleanField(default=False),
        ),
    ]
