# Generated by Django 5.2.10 on 2026-03-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_analytics_apikey_assignment_attendancesession_backup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='education_level',
            field=models.CharField(choices=[('olevel', 'O-Level (Form 1-4)'), ('alevel', 'A-Level (Form 5-6)'), ('primary', 'Primary School'), ('tertiary', 'Tertiary/University')], default='olevel', max_length=10),
        ),
    ]
