# Generated by Django 5.2.10 on 2026-03-06 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_department_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_form',
            field=models.PositiveIntegerField(choices=[(1, 'Form 1'), (2, 'Form 2'), (3, 'Form 3'), (4, 'Form 4')], default=1, help_text='Current form level for O-level students'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='necta_exam_number',
            field=models.CharField(blank=True, help_text='NECTA examination number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='previous_school',
            field=models.CharField(blank=True, help_text='Previous primary school', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='primary_school_leaving_exam_number',
            field=models.CharField(blank=True, help_text='PSLE number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_semester',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], help_text='For university-level students', null=True),
        ),
        migrations.CreateModel(
            name='SchoolCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField(choices=[(2020, '2020-2021'), (2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026'), (2026, '2026-2027'), (2027, '2027-2028'), (2028, '2028-2029'), (2029, '2029-2030'), (2030, '2030-2031'), (2031, '2031-2032'), (2032, '2032-2033'), (2033, '2033-2034'), (2034, '2034-2035')])),
                ('term', models.PositiveIntegerField(choices=[(1, 'Term I'), (2, 'Term II'), (3, 'Term III')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('teaching_weeks', models.PositiveIntegerField(default=12, help_text='Number of teaching weeks')),
                ('exam_weeks', models.PositiveIntegerField(default=2, help_text='Number of examination weeks')),
                ('holiday_weeks', models.PositiveIntegerField(default=4, help_text='Number of holiday weeks')),
            ],
            options={
                'ordering': ['-academic_year', 'term'],
                'unique_together': {('academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='NECTAExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('csee', 'Certificate of Secondary Education Examination (CSEE)'), ('ftna', 'Form Two National Assessment (FTNA)'), ('mock', 'Mock Examination'), ('terminal', 'Terminal Examination'), ('annual', 'Annual Examination')], max_length=10)),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English Language'), ('kisw', 'Kiswahili'), ('bio', 'Biology'), ('phy', 'Physics'), ('chem', 'Chemistry'), ('hist', 'History'), ('geo', 'Geography'), ('civ', 'Civics'), ('bkee', 'Bookkeeping'), ('comm', 'Commerce'), ('ict', 'Information & Computer Studies'), ('agri', 'Agriculture'), ('arb', 'Arabic Language'), ('fre', 'French Language'), ('home', 'Home Economics'), ('art', 'Art & Design'), ('music', 'Music'), ('p_e', 'Physical Education')], max_length=10)),
                ('grade', models.CharField(choices=[('A', 'A (75-100)'), ('B', 'B (65-74)'), ('C', 'C (45-64)'), ('D', 'D (30-44)'), ('F', 'F (0-29)')], max_length=1)),
                ('marks_obtained', models.PositiveIntegerField(blank=True, help_text='Marks out of 100', null=True)),
                ('exam_year', models.PositiveIntegerField()),
                ('exam_month', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('is_mock', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necta_exams', to='core.studentprofile')),
            ],
            options={
                'ordering': ['-exam_year', '-exam_month', 'subject'],
                'unique_together': {('student', 'exam_type', 'subject', 'exam_year', 'exam_month')},
            },
        ),
    ]
