# Generated by Django 5.2.10 on 2026-03-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_tanzania_olevel_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('MAT', 'Mathematics'), ('ENG', 'English Language'), ('PHY', 'Physics'), ('CHE', 'Chemistry'), ('KIS', 'Kiswahili'), ('BIO', 'Biology'), ('HIS', 'History'), ('GEO', 'Geography'), ('CIV', 'Civics'), ('COM', 'Commerce'), ('BK', 'Book Keeping'), ('ICS', 'Information and Computer Studies'), ('PE', 'Physical Education')], max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('form_level', models.CharField(choices=[('1', 'Form 1'), ('2', 'Form 2'), ('3', 'Form 3'), ('4', 'Form 4')], max_length=1)),
                ('is_core', models.BooleanField(default=True, help_text='Core subjects are compulsory')),
                ('is_optional', models.BooleanField(default=False, help_text='Optional subjects can be chosen by students')),
            ],
            options={
                'ordering': ['form_level', 'code'],
                'unique_together': {('code', 'form_level')},
            },
        ),
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField(help_text='Academic year for this enrollment')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='core.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.subject')),
            ],
            options={
                'ordering': ['academic_year', 'subject__code'],
                'unique_together': {('student', 'subject', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrolled_subjects',
            field=models.ManyToManyField(related_name='students', through='core.SubjectEnrollment', to='core.subject'),
        ),
    ]
