# Generated by Django 5.2.10 on 2026-03-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_tanzania_olevel_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
