# Generated by Django 5.2.10 on 2026-03-08 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_user_is_admin_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When should this announcement expire?', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('All', 'All'), ('Students', 'Students'), ('Faculty', 'Faculty'), ('Parents', 'Parents'), ('Class', 'Specific Class')], default='All', max_length=50),
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Class name (e.g., Form 1A, Form 2B)', max_length=50, unique=True)),
                ('form_level', models.PositiveIntegerField(choices=[(1, 'Form 1'), (2, 'Form 2'), (3, 'Form 3'), (4, 'Form 4')], help_text='Form level (1-4)')),
                ('max_students', models.PositiveIntegerField(default=40, help_text='Maximum number of students in this class')),
                ('current_students', models.PositiveIntegerField(default=0, help_text='Current number of students')),
                ('academic_year', models.PositiveIntegerField(help_text='Academic year for this class')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this class is currently active')),
                ('class_teacher', models.ForeignKey(blank=True, help_text='Class teacher assigned to this class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facultyprofile')),
                ('department', models.ForeignKey(help_text='Department this class belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'ordering': ['form_level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_class',
            field=models.ForeignKey(blank=True, help_text="Select class when target audience is 'Specific Class'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studentclass'),
        ),
        migrations.AddIndex(
            model_name='studentclass',
            index=models.Index(fields=['form_level', 'academic_year'], name='core_studen_form_le_d82ff1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentclass',
            unique_together={('name', 'academic_year')},
        ),
    ]
