# Generated by Django 5.2.10 on 2026-03-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_announcement_expires_at_announcement_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(blank=True, help_text='Time when student checked in', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(blank=True, help_text='Time when student checked out', null=True),
        ),
    ]
