# Generated by Django 5.2.10 on 2026-03-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_update_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(blank=True, help_text="Father's full name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(blank=True, help_text="Mother's full name", max_length=100, null=True),
        ),
    ]
